name: CI

on:
  push: 
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.x
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Regenerate files
      run: |
        ./hack/update-codegen.sh
    - name: Check for drift in generated files
      run: |
        git diff --exit-code .
    - name: Test
      run: |
        go test -v ./... -coverprofile cover.out
    - name: Report coverage
      run: |
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: 16421b44-8cd3-49d9-a01e-189c5141009e
